image: python:3.6

services:
  - mongo:latest

variables:
  Host: mongo

before_script:
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/ci/mc
  - export PATH=/home/ci/mc/bin:$PATH
  - conda config --set always_yes True
  - conda create -n testenv python=3.6 pytest coverage xlrd xlwt pymongo pandas -c conda-forge
  - source activate testenv
  - pip install flake8 codecov
  - echo "mongo" > sampleDB.conf

test:
  tags:
   - python
   - mongodb
  script:
   - coverage run run_tests.py
   - coverage report -m

after_script:
  - flake8 .
  - codecov
